version: 1

global:
  project_name: myapp

docker:
  builds:
  - name: app
    env:
      HOME: /tmp
      MYSQL_HOST: localhost
      SYMFONY_ENV: prod
      MYSQL_DATABASE:
        secret:
          name: db
          key: name
      MYSQL_USER:
        secret:
          name: db
          key: user
      MYSQL_PASSWORD:
        secret:
          name: db
          key: password
      SMTP_HOST:
        secret:
          name: smtp
          key: host
      SENTRY_DSN:
        secret:
          name: sentry
          key: dsn
      SENTRY_RELEASE: "%shortcommit%"
      SENTRY_NAME: fed
      PS_SECRET:
        secret:
          name: ps
          key: secret
      PS_COOKIE_KEY:
        secret:
          name: ps
          key: cookiekey
      PS_COOKIE_IV:
        secret:
          name: ps
          key: cookieiv
      PS_NEW_COOKIE_KEY:
        secret:
          name: ps
          key: newcookiekey
      MYSQL1:
        secret:
          name: mysql
          key: node1
      MYSQL2:
        secret:
          name: mysql
          key: node2
      MYSQL3:
        secret:
          name: mysql
          key: node3
      PROXYSQL_ADMIN_PASSWORD:
        secret:
          name: proxysql
          key: admin_password
      PROXYSQL_MONITOR_PASSWORD:
        secret:
          name: proxysql
          key: monitor_password
    volumes:
      - path: /data/img
        name: img
        size: 10G
        type: nas
      - path: /data/htdocs/upload
        name: upload
        size: 10G
        type: nas

deploy:
  - name: app
    cpu: 0.1
    mem: 512
    docker:
      build: app
    ports:
      - name: http
        number: 8080
        check:
          type: http
          path: /ping.php
        routing:
          develop:
            domains:
            - preprod.myapp.com
            auth:
              user: private
              password: app
          master:
            domains:
            - www.myapp.com
