version: '3'
services:
  mysql:
    command: mysqld --max_allowed_packet=16M
    image: mariadb
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    networks:
      - back
      - proxy
    ports:
      - "127.0.0.1:${PMA_PORT}:80"
  memcache:
    image: memcached:alpine
    networks:
      - back
  app:
    build:
      context: .
      args:
        PHP_UID: ${PHP_UID:-33}
    volumes:
      - ./app:/data/htdocs:cached
      - /data/htdocs/app/cache
      #- ./upload:/data/htdocs/upload:cached
      #- ./logs:/data/htdocs/app/logs:cached
      - ./config/php-dev:/usr/local/etc/php-fpm.d:cached
      - ./config/nginx/rewrite.map:/etc/nginx/rewrite.map:cached
    networks:
      - back
      - proxy
    ports:
      - "80"
      - "127.0.0.1:${APP_PORT}:9090"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SYMFONY_ENV=${ENV}
      - VERSION=dev
      - SENTRY_RELEASE=dev
      - SENTRY_NAME=PSTEST
      - SENTRY_DSN=${SENTRY_DSN}
      - PS_SECRET=${PS_SECRET}
      - PS_COOKIE_KEY=${PS_COOKIE_KEY}
      - PS_COOKIE_IV=${PS_COOKIE_IV}
      - PS_NEW_COOKIE_KEY=${PS_NEW_COOKIE_KEY}
      - ADMIN_FOLDER=${ADMIN_FOLDER}
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - COMPOSER_HOME=/tmp

  proxy:
    image: haproxy
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
    networks:
      - proxy
    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
      - "127.0.0.1:${HTTPS_PORT}:443"

  mailhog:
    image: mailhog/mailhog
    user: root
    networks:
      - back
      - proxy
    ports:
      - "127.0.0.1:${MAILHOG_PORT}:8025"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25

volumes:
  mysql-data:
    driver: local

networks:
  back:
  proxy:
