admin_variables =
{
        admin_credentials="ADMIN_USER:ADMIN_PASSWORD"
        checksum_mysql_query_rules="true"
        checksum_mysql_servers="true"
        checksum_mysql_users="true"
        cluster_check_interval_ms="1000"
        cluster_check_status_frequency="10"
        cluster_mysql_query_rules_diffs_before_sync="3"
        cluster_mysql_query_rules_save_to_disk="true"
        cluster_mysql_servers_diffs_before_sync="3"
        cluster_mysql_servers_save_to_disk="true"
        cluster_mysql_users_diffs_before_sync="3"
        cluster_mysql_users_save_to_disk="true"
        cluster_proxysql_servers_diffs_before_sync="3"
        cluster_proxysql_servers_save_to_disk="true"
        hash_passwords="true"
        mysql_ifaces="0.0.0.0:6032"
        read_only="false"
        refresh_interval="2000"
        restapi_enabled="false"
        restapi_port="6070"
        stats_credentials="stats:stats"
        stats_mysql_connection_pool="60"
        stats_mysql_connections="60"
        stats_mysql_query_cache="60"
        stats_mysql_query_digest_to_disk="0"
        stats_system_cpu="60"
        stats_system_memory="60"
        telnet_admin_ifaces="(null)"
        telnet_stats_ifaces="(null)"
        vacuum_stats="true"
        version="2.0.11-123-g504da773"
        web_enabled="false"
        web_port="6080"
}

mysql_variables =
{
        auditlog_filesize="104857600"
        aurora_max_lag_ms_only_read_from_replicas="2"
        auto_increment_delay_multiplex="5"
        autocommit_false_is_transaction="false"
        autocommit_false_not_reusable="false"
        automatic_detect_sqli="0"
        binlog_reader_connect_retry_msec="3000"
        client_found_rows="true"
        client_multi_statements="true"
        client_session_track_gtid="true"
        commands_stats="true"
        connect_retries_delay="1"
        connect_retries_on_failure="10"
        connect_timeout_server="1000"
        connect_timeout_server_max="10000"
        connection_delay_multiplex_ms="0"
        connection_max_age_ms="0"
        connection_warming="false"
        connpoll_reset_queue_length="50"
        default_CHARSET="utf8"
        default_character_set_client="utf8"
        default_character_set_connection="utf8"
        default_character_set_database="utf8"
        default_character_set_results="utf8"
        default_charset="utf8"
        default_collation_connection="utf8_general_ci"
        default_max_latency_ms="1000"
        default_query_delay="0"
        default_query_timeout="86400000"
        default_reconnect="true"
        default_schema="information_schema"
        default_session_track_gtids="OFF"
        default_time_zone="SYSTEM"
        default_tx_isolation="READ-COMMITTED"
        enforce_autocommit_on_reads="false"
        eventslog_default_log="0"
        eventslog_filesize="104857600"
        eventslog_format="1"
        firewall_whitelist_enabled="0"
        firewall_whitelist_errormsg="Firewall blocked this query"
        forward_autocommit="false"
        free_connections_pct="10"
        interfaces="0.0.0.0:3306;/tmp/mysqld.sock"
        handle_unknown_charset="1"
        have_compress="true"
        have_ssl="false"
        hostgroup_manager_verbose="1"
        keep_multiplexing_variables="tx_isolation,version"
        kill_backend_connection_when_disconnect="true"
        log_unhealthy_connections="true"
        long_query_time="1000"
        max_allowed_packet="4194304"
        max_connections="10000"
        max_stmts_cache="10000"
        max_stmts_per_connection="20"
        max_transaction_time="14400000"
        min_num_servers_lantency_awareness="1000"
        mirror_max_concurrency="16"
        mirror_max_queue_length="32000"
        monitor_connect_interval="120000"
        monitor_connect_timeout="600"
        monitor_enabled="true"
        monitor_galera_healthcheck_interval="5000"
        monitor_galera_healthcheck_max_timeout_count="3"
        monitor_galera_healthcheck_timeout="800"
        monitor_groupreplication_healthcheck_interval="5000"
        monitor_groupreplication_healthcheck_max_timeout_count="3"
        monitor_groupreplication_healthcheck_timeout="800"
        monitor_groupreplication_max_transactions_behind_count="3"
        monitor_history="600000"
        monitor_password="MONITOR_PASSWORD"
        monitor_ping_interval="8000"
        monitor_ping_max_failures="3"
        monitor_ping_timeout="1000"
        monitor_query_interval="60000"
        monitor_query_timeout="100"
        monitor_read_only_interval="1000"
        monitor_read_only_max_timeout_count="3"
        monitor_read_only_timeout="800"
        monitor_replication_lag_interval="10000"
        monitor_replication_lag_timeout="1000"
        monitor_slave_lag_when_null="60"
        monitor_threads_max="128"
        monitor_threads_min="8"
        monitor_threads_queue_maxsize="128"
        monitor_username="monitor"
        monitor_wait_timeout="true"
        monitor_writer_is_also_reader="true"
        multiplexing="true"
        ping_interval_server_msec="10000"
        ping_timeout_server="200"
        poll_timeout="2000"
        poll_timeout_on_failure="100"
        query_cache_size_MB="256"
        query_cache_stores_empty_result="true"
        query_digests="true"
        query_digests_lowercase="false"
        query_digests_max_digest_length="2048"
        query_digests_max_query_length="65000"
        query_digests_no_digits="false"
        query_digests_normalize_digest_text="false"
        query_digests_replace_null="false"
        query_digests_track_hostname="false"
        query_processor_iterations="0"
        query_processor_regex="1"
        query_retries_on_failure="1"
        reset_connection_algorithm="2"
        server_capabilities="569899"
        server_version="5.5.30"
        servers_stats="true"
        session_idle_ms="1000"
        session_idle_show_processlist="true"
        sessions_sort="true"
        set_query_lock_on_hostgroup="1"
        show_processlist_extended="0"
        shun_on_failures="5"
        shun_recovery_time_sec="10"
        stacksize="1048576"
        stats_time_backend_query="false"
        stats_time_query_processor="false"
        tcp_keepalive_time="0"
        threads="4"
        threshold_query_length="524288"
        threshold_resultset_size="4194304"
        throttle_connections_per_sec_to_hostgroup="1000000"
        throttle_max_bytes_per_second_to_client="0"
        throttle_ratio_server_to_client="0"
        use_tcp_keepalive="0"
        verbose_query_error="false"
        wait_timeout="28800000"
}
mysql_users:
(
        {
                username = "MYSQL_USER"
                password = "MYSQL_PASSWORD"
                default_hostgroup = 2
        }
)
mysql_servers:
(
        {
                hostgroup_id=2
                hostname="MYSQL1",weight=1
                port=3306
                max_connections=1000
                max_latency_ms=50
        },
        {
                hostgroup_id=2
                hostname="MYSQL2",weight=1
                port=3306
                max_connections=1000
                max_latency_ms=50
        },
        {
                hostgroup_id=2
                hostname="MYSQL3",weight=1
                port=3306
                max_connections=1000
                max_latency_ms=50
        }
)
mysql_galera_hostgroups:
(
        {
                writer_hostgroup=2
                backup_writer_hostgroup=4
                reader_hostgroup=3
                offline_hostgroup=1
                active=1
                max_writers=1
                writer_is_also_reader=1
                max_transactions_behind=100
        }
)
